# Generated by Django 3.1.6 on 2021-02-24 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vinerfiav1', '0002_auto_20210224_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True)),
                ('orderNumber', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('subtotal', models.FloatField(default=0.0)),
                ('shipping', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='vinerfiav1.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
