# Generated by Django 3.1.6 on 2021-02-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinerfiav1', '0004_auto_20210225_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
